version: '3'
services:
  tictactoe:
    build: ./images/tictactoe/.
    image: tictactoe/tictactoe
    ports:
      - 8001:8001
    networks:
      - tictactoe
    volumes:
       - "/etc/bss/configuration:/etc/bss/configuration"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
  postgres:
    build: ./images/postgres/.
    image: tictactoe/postgres
    ports:
      - 5433:5432
    networks:
      - tictactoe
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  tictactoe:
    external: false
    driver: overlay